management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
  port: 8082

resilience4j.ratelimiter:
    instances:
      apiRateLimiter:
        limit-for-period: 10
        limit-refresh-period: 10s
        timeout-duration: 0

resilience4j.circuitbreaker:
  instances:
    apiCircuitBreaker:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3
      sliding-window-type: count_based
      sliding-window-size: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:29093

topic-to-send-message: audit_topic
